ontologyVersionInfo('',literal(lang(en,'v.1.4. Added Food class (used in domain/range of hasIngredient), Added several hasCountryOfOrigin restrictions on pizzas, Made hasTopping invers functional'))).
ontologyVersionInfo('',literal(type('http://www.w3.org/2001/XMLSchema#string','version 1.5'))).
ontologyVersionInfo('',literal(lang(en,'v.1.5. Removed protege.owl import and references. Made ontology URI date-independent'))).
ontology('').
class('#American').
class('#NamedPizza').
class('#MozzarellaTopping').
class('#PeperoniSausageTopping').
class('#TomatoTopping').
class('#AmericanHot').
class('#JalapenoPepperTopping').
class('#HotGreenPepperTopping').
class('#AnchoviesTopping').
class('#FishTopping').
class('#ArtichokeTopping').
class('#VegetableTopping').
class('#AsparagusTopping').
class('#Cajun').
class('#PrawnsTopping').
class('#TobascoPepperSauce').
class('#OnionTopping').
class('#PeperonataTopping').
class('#CajunSpiceTopping').
class('#HerbSpiceTopping').
class('#CaperTopping').
class('#Capricciosa').
class('#HamTopping').
class('#OliveTopping').
class('#Caprina').
class('#SundriedTomatoTopping').
class('#GoatsCheeseTopping').
class('#CheeseTopping').
class('#PizzaTopping').
class('#CheeseyPizza').
class('#Pizza').
class('#CheeseyVegetableTopping').
class('#ChickenTopping').
class('#MeatTopping').
class('#Country').
class('#DomainConcept').
class('#DeepPanBase').
class('#PizzaBase').
class('#Fiorentina').
class('#GarlicTopping').
class('#SpinachTopping').
class('#ParmesanTopping').
class('#Food').
class('#FourCheesesTopping').
class('#FourSeasons').
class('#MushroomTopping').
class('#FruitTopping').
class('#FruttiDiMare').
class('#MixedSeafoodTopping').
class('#Giardiniera').
class('#LeekTopping').
class('#PetitPoisTopping').
class('#SlicedTomatoTopping').
class('#GorgonzolaTopping').
class('#GreenPepperTopping').
class('#PepperTopping').
class('#Hot').
class('#Spiciness').
class('#HotSpicedBeefTopping').
class('#IceCream').
class('#InterestingPizza').
class('#LaReine').
class('#Margherita').
class('#MeatyPizza').
class('#Medium').
class('#Mild').
class('#Mushroom').
class('#Napoletana').
class('#NonVegetarianPizza').
class('#VegetarianPizza').
class('#NutTopping').
class('#ParmaHamTopping').
class('#Parmense').
class('#PineKernels').
class('#PolloAdAstra').
class('#RedOnionTopping').
class('#SweetPepperTopping').
class('#PrinceCarlo').
class('#RosemaryTopping').
class('#QuattroFormaggi').
class('#RealItalianPizza').
class('#RocketTopping').
class('#Rosa').
class('#SauceTopping').
class('#Siciliana').
class('#SloppyGiuseppe').
class('#Soho').
class('#ValuePartition').
class('#SpicyPizza').
class('#SpicyPizzaEquivalent').
class('#SpicyTopping').
class('#SultanaTopping').
class('#ThinAndCrispyBase').
class('#ThinAndCrispyPizza').
class('#UnclosedPizza').
class('#VegetarianPizzaEquivalent1').
class('#VegetarianPizzaEquivalent2').
class('#VegetarianTopping').
class('#Veneziana').
objectProperty('#hasBase').
objectProperty('#isBaseOf').
objectProperty('#hasCountryOfOrigin').
objectProperty('#hasIngredient').
objectProperty('#isIngredientOf').
objectProperty('#hasSpiciness').
objectProperty('#hasTopping').
objectProperty('#isToppingOf').
subClassOf('#American',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#American',someValuesFrom('#hasTopping','#PeperoniSausageTopping')).
subClassOf('#American',hasValue('#hasCountryOfOrigin','#America')).
subClassOf('#American',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#American','#NamedPizza').
subClassOf('#American',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#PeperoniSausageTopping','#TomatoTopping']))).
subClassOf('#AmericanHot',someValuesFrom('#hasTopping','#HotGreenPepperTopping')).
subClassOf('#AmericanHot',someValuesFrom('#hasTopping','#JalapenoPepperTopping')).
subClassOf('#AmericanHot',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#AmericanHot',hasValue('#hasCountryOfOrigin','#America')).
subClassOf('#AmericanHot',someValuesFrom('#hasTopping','#PeperoniSausageTopping')).
subClassOf('#AmericanHot',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#AmericanHot','#NamedPizza').
subClassOf('#AmericanHot',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#PeperoniSausageTopping','#JalapenoPepperTopping','#TomatoTopping','#HotGreenPepperTopping']))).
subClassOf('#AnchoviesTopping','#FishTopping').
subClassOf('#ArtichokeTopping','#VegetableTopping').
subClassOf('#ArtichokeTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#AsparagusTopping','#VegetableTopping').
subClassOf('#AsparagusTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#Cajun',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Cajun',someValuesFrom('#hasTopping','#TobascoPepperSauce')).
subClassOf('#Cajun',allValuesFrom('#hasTopping',unionOf(['#PrawnsTopping','#TobascoPepperSauce','#MozzarellaTopping','#TomatoTopping','#OnionTopping','#PeperonataTopping']))).
subClassOf('#Cajun',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Cajun',someValuesFrom('#hasTopping','#OnionTopping')).
subClassOf('#Cajun',someValuesFrom('#hasTopping','#PeperonataTopping')).
subClassOf('#Cajun','#NamedPizza').
subClassOf('#Cajun',someValuesFrom('#hasTopping','#PrawnsTopping')).
subClassOf('#CajunSpiceTopping',someValuesFrom('#hasSpiciness','#Hot')).
subClassOf('#CajunSpiceTopping','#HerbSpiceTopping').
subClassOf('#CaperTopping','#VegetableTopping').
subClassOf('#CaperTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#HamTopping')).
subClassOf('#Capricciosa',allValuesFrom('#hasTopping',unionOf(['#AnchoviesTopping','#MozzarellaTopping','#TomatoTopping','#PeperonataTopping','#HamTopping','#CaperTopping','#OliveTopping']))).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#AnchoviesTopping')).
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#PeperonataTopping')).
subClassOf('#Capricciosa','#NamedPizza').
subClassOf('#Capricciosa',someValuesFrom('#hasTopping','#CaperTopping')).
subClassOf('#Caprina',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Caprina',someValuesFrom('#hasTopping','#SundriedTomatoTopping')).
subClassOf('#Caprina',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Caprina','#NamedPizza').
subClassOf('#Caprina',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#SundriedTomatoTopping','#GoatsCheeseTopping']))).
subClassOf('#Caprina',someValuesFrom('#hasTopping','#GoatsCheeseTopping')).
subClassOf('#CheeseTopping','#PizzaTopping').
subClassOf('#CheeseyVegetableTopping','#CheeseTopping').
subClassOf('#CheeseyVegetableTopping','#VegetableTopping').
subClassOf('#ChickenTopping','#MeatTopping').
subClassOf('#ChickenTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#DeepPanBase','#PizzaBase').
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Fiorentina',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#GarlicTopping','#TomatoTopping','#SpinachTopping','#OliveTopping','#ParmesanTopping']))).
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#GarlicTopping')).
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#ParmesanTopping')).
subClassOf('#Fiorentina',someValuesFrom('#hasTopping','#SpinachTopping')).
subClassOf('#Fiorentina','#NamedPizza').
subClassOf('#FishTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#FishTopping','#PizzaTopping').
subClassOf('#Food','#DomainConcept').
subClassOf('#FourCheesesTopping','#CheeseTopping').
subClassOf('#FourCheesesTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#MushroomTopping')).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#PeperoniSausageTopping')).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#FourSeasons',allValuesFrom('#hasTopping',unionOf(['#AnchoviesTopping','#MozzarellaTopping','#PeperoniSausageTopping','#TomatoTopping','#CaperTopping','#OliveTopping','#MushroomTopping']))).
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#AnchoviesTopping')).
subClassOf('#FourSeasons','#NamedPizza').
subClassOf('#FourSeasons',someValuesFrom('#hasTopping','#CaperTopping')).
subClassOf('#FruitTopping','#PizzaTopping').
subClassOf('#FruttiDiMare',allValuesFrom('#hasTopping',unionOf(['#GarlicTopping','#TomatoTopping','#MixedSeafoodTopping']))).
subClassOf('#FruttiDiMare',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#FruttiDiMare',someValuesFrom('#hasTopping','#GarlicTopping')).
subClassOf('#FruttiDiMare',someValuesFrom('#hasTopping','#MixedSeafoodTopping')).
subClassOf('#FruttiDiMare','#NamedPizza').
subClassOf('#GarlicTopping','#VegetableTopping').
subClassOf('#GarlicTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#MushroomTopping')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Giardiniera',allValuesFrom('#hasTopping',unionOf(['#LeekTopping','#MozzarellaTopping','#TomatoTopping','#PetitPoisTopping','#PeperonataTopping','#OliveTopping','#MushroomTopping','#SlicedTomatoTopping']))).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#SlicedTomatoTopping')).
subClassOf('#Giardiniera','#NamedPizza').
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#PeperonataTopping')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#PetitPoisTopping')).
subClassOf('#Giardiniera',someValuesFrom('#hasTopping','#LeekTopping')).
subClassOf('#GoatsCheeseTopping','#CheeseTopping').
subClassOf('#GoatsCheeseTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#GorgonzolaTopping','#CheeseTopping').
subClassOf('#GorgonzolaTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#GreenPepperTopping','#PepperTopping').
subClassOf('#HamTopping','#MeatTopping').
subClassOf('#HerbSpiceTopping','#PizzaTopping').
subClassOf('#Hot','#Spiciness').
subClassOf('#HotGreenPepperTopping',someValuesFrom('#hasSpiciness','#Hot')).
subClassOf('#HotGreenPepperTopping','#GreenPepperTopping').
subClassOf('#HotSpicedBeefTopping','#MeatTopping').
subClassOf('#HotSpicedBeefTopping',someValuesFrom('#hasSpiciness','#Hot')).
subClassOf('#IceCream',someValuesFrom('#hasTopping','#FruitTopping')).
subClassOf('#IceCream','#Food').
subClassOf('#JalapenoPepperTopping',someValuesFrom('#hasSpiciness','#Hot')).
subClassOf('#JalapenoPepperTopping','#PepperTopping').
subClassOf('#LaReine',someValuesFrom('#hasTopping','#MushroomTopping')).
subClassOf('#LaReine',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#LaReine',someValuesFrom('#hasTopping','#HamTopping')).
subClassOf('#LaReine',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#LaReine',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#LaReine','#NamedPizza').
subClassOf('#LaReine',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#HamTopping','#OliveTopping','#MushroomTopping']))).
subClassOf('#LeekTopping','#VegetableTopping').
subClassOf('#LeekTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#Margherita',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Margherita',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Margherita',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping']))).
subClassOf('#Margherita','#NamedPizza').
subClassOf('#MeatTopping','#PizzaTopping').
subClassOf('#Medium','#Spiciness').
subClassOf('#Mild','#Spiciness').
subClassOf('#MixedSeafoodTopping','#FishTopping').
subClassOf('#MozzarellaTopping','#CheeseTopping').
subClassOf('#MozzarellaTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#MozzarellaTopping',hasValue('#hasCountryOfOrigin','#Italy')).
subClassOf('#Mushroom',someValuesFrom('#hasTopping','#MushroomTopping')).
subClassOf('#Mushroom',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#MushroomTopping']))).
subClassOf('#Mushroom',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Mushroom',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Mushroom','#NamedPizza').
subClassOf('#MushroomTopping','#VegetableTopping').
subClassOf('#MushroomTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#NamedPizza','#Pizza').
subClassOf('#Napoletana',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Napoletana',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Napoletana',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Napoletana',someValuesFrom('#hasTopping','#AnchoviesTopping')).
subClassOf('#Napoletana','#NamedPizza').
subClassOf('#Napoletana',hasValue('#hasCountryOfOrigin','#Italy')).
subClassOf('#Napoletana',someValuesFrom('#hasTopping','#CaperTopping')).
subClassOf('#Napoletana',allValuesFrom('#hasTopping',unionOf(['#AnchoviesTopping','#MozzarellaTopping','#TomatoTopping','#CaperTopping','#OliveTopping']))).
subClassOf('#NutTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#NutTopping','#PizzaTopping').
subClassOf('#OliveTopping','#VegetableTopping').
subClassOf('#OliveTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#OnionTopping','#VegetableTopping').
subClassOf('#OnionTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#ParmaHamTopping','#HamTopping').
subClassOf('#ParmaHamTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#Parmense',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Parmense',someValuesFrom('#hasTopping','#HamTopping')).
subClassOf('#Parmense',someValuesFrom('#hasTopping','#ParmesanTopping')).
subClassOf('#Parmense',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Parmense','#NamedPizza').
subClassOf('#Parmense',someValuesFrom('#hasTopping','#AsparagusTopping')).
subClassOf('#Parmense',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#HamTopping','#ParmesanTopping','#AsparagusTopping']))).
subClassOf('#ParmesanTopping','#CheeseTopping').
subClassOf('#ParmesanTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#PeperonataTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#PeperonataTopping','#PepperTopping').
subClassOf('#PeperoniSausageTopping','#MeatTopping').
subClassOf('#PeperoniSausageTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#PepperTopping','#VegetableTopping').
subClassOf('#PetitPoisTopping','#VegetableTopping').
subClassOf('#PetitPoisTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#PineKernels','#NutTopping').
subClassOf('#Pizza','#Food').
subClassOf('#Pizza',someValuesFrom('#hasBase','#PizzaBase')).
subClassOf('#PizzaBase','#Food').
subClassOf('#PizzaTopping','#Food').
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#RedOnionTopping')).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#CajunSpiceTopping')).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#GarlicTopping')).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#SweetPepperTopping')).
subClassOf('#PolloAdAstra',allValuesFrom('#hasTopping',unionOf(['#ChickenTopping','#MozzarellaTopping','#GarlicTopping','#TomatoTopping','#RedOnionTopping','#CajunSpiceTopping','#SweetPepperTopping']))).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#PolloAdAstra',someValuesFrom('#hasTopping','#ChickenTopping')).
subClassOf('#PolloAdAstra','#NamedPizza').
subClassOf('#PrawnsTopping','#FishTopping').
subClassOf('#PrinceCarlo',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#PrinceCarlo',allValuesFrom('#hasTopping',unionOf(['#LeekTopping','#RosemaryTopping','#MozzarellaTopping','#TomatoTopping','#ParmesanTopping']))).
subClassOf('#PrinceCarlo',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#PrinceCarlo',someValuesFrom('#hasTopping','#ParmesanTopping')).
subClassOf('#PrinceCarlo','#NamedPizza').
subClassOf('#PrinceCarlo',someValuesFrom('#hasTopping','#LeekTopping')).
subClassOf('#PrinceCarlo',someValuesFrom('#hasTopping','#RosemaryTopping')).
subClassOf('#QuattroFormaggi',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#QuattroFormaggi','#NamedPizza').
subClassOf('#QuattroFormaggi',someValuesFrom('#hasTopping','#FourCheesesTopping')).
subClassOf('#QuattroFormaggi',allValuesFrom('#hasTopping',unionOf(['#FourCheesesTopping','#TomatoTopping']))).
subClassOf('#RealItalianPizza',allValuesFrom('#hasBase','#ThinAndCrispyBase')).
subClassOf('#RedOnionTopping','#OnionTopping').
subClassOf('#RocketTopping','#VegetableTopping').
subClassOf('#RocketTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#Rosa',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Rosa',someValuesFrom('#hasTopping','#GorgonzolaTopping')).
subClassOf('#Rosa',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#GorgonzolaTopping']))).
subClassOf('#Rosa',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Rosa','#NamedPizza').
subClassOf('#RosemaryTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#RosemaryTopping','#HerbSpiceTopping').
subClassOf('#SauceTopping','#PizzaTopping').
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#GarlicTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#HamTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#ArtichokeTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Siciliana',someValuesFrom('#hasTopping','#AnchoviesTopping')).
subClassOf('#Siciliana','#NamedPizza').
subClassOf('#Siciliana',allValuesFrom('#hasTopping',unionOf(['#AnchoviesTopping','#MozzarellaTopping','#GarlicTopping','#ArtichokeTopping','#TomatoTopping','#HamTopping','#OliveTopping']))).
subClassOf('#SlicedTomatoTopping','#TomatoTopping').
subClassOf('#SlicedTomatoTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#SloppyGiuseppe',someValuesFrom('#hasTopping','#HotSpicedBeefTopping')).
subClassOf('#SloppyGiuseppe',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#SloppyGiuseppe',someValuesFrom('#hasTopping','#GreenPepperTopping')).
subClassOf('#SloppyGiuseppe',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#SloppyGiuseppe',someValuesFrom('#hasTopping','#OnionTopping')).
subClassOf('#SloppyGiuseppe',allValuesFrom('#hasTopping',unionOf(['#HotSpicedBeefTopping','#MozzarellaTopping','#TomatoTopping','#OnionTopping','#GreenPepperTopping']))).
subClassOf('#SloppyGiuseppe','#NamedPizza').
subClassOf('#Soho',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Soho',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#GarlicTopping','#TomatoTopping','#RocketTopping','#OliveTopping','#ParmesanTopping']))).
subClassOf('#Soho',someValuesFrom('#hasTopping','#GarlicTopping')).
subClassOf('#Soho',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Soho',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Soho',someValuesFrom('#hasTopping','#ParmesanTopping')).
subClassOf('#Soho','#NamedPizza').
subClassOf('#Soho',someValuesFrom('#hasTopping','#RocketTopping')).
subClassOf('#Spiciness','#ValuePartition').
subClassOf('#SpinachTopping','#VegetableTopping').
subClassOf('#SpinachTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#SultanaTopping','#FruitTopping').
subClassOf('#SultanaTopping',someValuesFrom('#hasSpiciness','#Medium')).
subClassOf('#SundriedTomatoTopping','#TomatoTopping').
subClassOf('#SundriedTomatoTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#SweetPepperTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#SweetPepperTopping','#PepperTopping').
subClassOf('#ThinAndCrispyBase','#PizzaBase').
subClassOf('#TobascoPepperSauce','#SauceTopping').
subClassOf('#TobascoPepperSauce',someValuesFrom('#hasSpiciness','#Hot')).
subClassOf('#TomatoTopping','#VegetableTopping').
subClassOf('#TomatoTopping',someValuesFrom('#hasSpiciness','#Mild')).
subClassOf('#UnclosedPizza',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#UnclosedPizza','#NamedPizza').
subClassOf('#VegetableTopping','#PizzaTopping').
subClassOf('#Veneziana',allValuesFrom('#hasTopping',unionOf(['#MozzarellaTopping','#TomatoTopping','#SultanaTopping','#OnionTopping','#CaperTopping','#OliveTopping','#PineKernels']))).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#PineKernels')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#TomatoTopping')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#OliveTopping')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#SultanaTopping')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#MozzarellaTopping')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#OnionTopping')).
subClassOf('#Veneziana','#NamedPizza').
subClassOf('#Veneziana',hasValue('#hasCountryOfOrigin','#Italy')).
subClassOf('#Veneziana',someValuesFrom('#hasTopping','#CaperTopping')).
equivalentClasses(['#CheeseyPizza',intersectionOf(['#Pizza',someValuesFrom('#hasTopping','#CheeseTopping')])]).
equivalentClasses(['#Country',intersectionOf([oneOf(['#America','#Italy','#Germany','#France','#England']),'#DomainConcept'])]).
equivalentClasses(['#InterestingPizza',intersectionOf([minCardinality(3,'#hasTopping'),'#Pizza'])]).
equivalentClasses(['#MeatyPizza',intersectionOf([someValuesFrom('#hasTopping','#MeatTopping'),'#Pizza'])]).
equivalentClasses(['#NonVegetarianPizza',intersectionOf(['#Pizza',complementOf('#VegetarianPizza')])]).
equivalentClasses(['#RealItalianPizza',intersectionOf(['#Pizza',hasValue('#hasCountryOfOrigin','#Italy')])]).
equivalentClasses(['#Spiciness',unionOf(['#Hot','#Medium','#Mild'])]).
equivalentClasses(['#SpicyPizza',intersectionOf(['#Pizza',someValuesFrom('#hasTopping','#SpicyTopping')])]).
equivalentClasses(['#SpicyPizzaEquivalent',intersectionOf(['#Pizza',someValuesFrom('#hasTopping',intersectionOf([someValuesFrom('#hasSpiciness','#Hot'),'#PizzaTopping']))])]).
equivalentClasses(['#SpicyTopping',intersectionOf([someValuesFrom('#hasSpiciness','#Hot'),'#PizzaTopping'])]).
equivalentClasses(['#ThinAndCrispyPizza',intersectionOf(['#Pizza',allValuesFrom('#hasBase','#ThinAndCrispyBase')])]).
equivalentClasses(['#VegetarianPizza',intersectionOf(['#Pizza',complementOf(someValuesFrom('#hasTopping','#MeatTopping')),complementOf(someValuesFrom('#hasTopping','#FishTopping'))])]).
equivalentClasses(['#VegetarianPizzaEquivalent1',intersectionOf(['#Pizza',allValuesFrom('#hasTopping','#VegetarianTopping')])]).
equivalentClasses(['#VegetarianPizzaEquivalent2',intersectionOf(['#Pizza',allValuesFrom('#hasTopping',unionOf(['#SauceTopping','#CheeseTopping','#VegetableTopping','#FruitTopping','#NutTopping','#HerbSpiceTopping']))])]).
equivalentClasses(['#VegetarianTopping',intersectionOf(['#PizzaTopping',unionOf(['#SauceTopping','#CheeseTopping','#VegetableTopping','#FruitTopping','#NutTopping','#HerbSpiceTopping'])])]).
disjointClasses(['#LaReine','#Mushroom']).
disjointClasses(['#Mushroom','#LaReine']).
disjointClasses(['#Veneziana','#Napoletana']).
disjointClasses(['#Napoletana','#Veneziana']).
disjointClasses(['#UnclosedPizza','#AmericanHot']).
disjointClasses(['#AmericanHot','#UnclosedPizza']).
disjointClasses(['#Mushroom','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Mushroom']).
disjointClasses(['#LeekTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#LeekTopping']).
disjointClasses(['#SpinachTopping','#OnionTopping']).
disjointClasses(['#OnionTopping','#SpinachTopping']).
disjointClasses(['#LaReine','#Capricciosa']).
disjointClasses(['#Capricciosa','#LaReine']).
disjointClasses(['#Mushroom','#Capricciosa']).
disjointClasses(['#Capricciosa','#Mushroom']).
disjointClasses(['#FruttiDiMare','#Veneziana']).
disjointClasses(['#Veneziana','#FruttiDiMare']).
disjointClasses(['#ArtichokeTopping','#GarlicTopping']).
disjointClasses(['#GarlicTopping','#ArtichokeTopping']).
disjointClasses(['#Siciliana','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Siciliana']).
disjointClasses(['#Mushroom','#Cajun']).
disjointClasses(['#Cajun','#Mushroom']).
disjointClasses(['#UnclosedPizza','#Margherita']).
disjointClasses(['#Margherita','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#American']).
disjointClasses(['#American','#UnclosedPizza']).
disjointClasses(['#SauceTopping','#MeatTopping']).
disjointClasses(['#MeatTopping','#SauceTopping']).
disjointClasses(['#FruttiDiMare','#AmericanHot']).
disjointClasses(['#AmericanHot','#FruttiDiMare']).
disjointClasses(['#SloppyGiuseppe','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#SloppyGiuseppe']).
disjointClasses(['#GarlicTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#GarlicTopping']).
disjointClasses(['#Caprina','#Capricciosa']).
disjointClasses(['#Capricciosa','#Caprina']).
disjointClasses(['#HotSpicedBeefTopping','#PeperoniSausageTopping']).
disjointClasses(['#PeperoniSausageTopping','#HotSpicedBeefTopping']).
disjointClasses(['#Caprina','#Soho']).
disjointClasses(['#Soho','#Caprina']).
disjointClasses(['#CheeseTopping','#VegetableTopping']).
disjointClasses(['#VegetableTopping','#CheeseTopping']).
disjointClasses(['#Soho','#American']).
disjointClasses(['#American','#Soho']).
disjointClasses(['#FruttiDiMare','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#FruttiDiMare']).
disjointClasses(['#FruttiDiMare','#Parmense']).
disjointClasses(['#Parmense','#FruttiDiMare']).
disjointClasses(['#LeekTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#LeekTopping']).
disjointClasses(['#OnionTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#OnionTopping']).
disjointClasses(['#Siciliana','#Margherita']).
disjointClasses(['#Margherita','#Siciliana']).
disjointClasses(['#Siciliana','#Napoletana']).
disjointClasses(['#Napoletana','#Siciliana']).
disjointClasses(['#LaReine','#Cajun']).
disjointClasses(['#Cajun','#LaReine']).
disjointClasses(['#Caprina','#American']).
disjointClasses(['#American','#Caprina']).
disjointClasses(['#Fiorentina','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Fiorentina']).
disjointClasses(['#Mushroom','#Fiorentina']).
disjointClasses(['#Fiorentina','#Mushroom']).
disjointClasses(['#Hot','#Mild']).
disjointClasses(['#Mild','#Hot']).
disjointClasses(['#Fiorentina','#Cajun']).
disjointClasses(['#Cajun','#Fiorentina']).
disjointClasses(['#OliveTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#OliveTopping']).
disjointClasses(['#CaperTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#CaperTopping']).
disjointClasses(['#SauceTopping','#FishTopping']).
disjointClasses(['#FishTopping','#SauceTopping']).
disjointClasses(['#UnclosedPizza','#Soho']).
disjointClasses(['#Soho','#UnclosedPizza']).
disjointClasses(['#Soho','#Parmense']).
disjointClasses(['#Parmense','#Soho']).
disjointClasses(['#FruttiDiMare','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#FruttiDiMare']).
disjointClasses(['#Fiorentina','#American']).
disjointClasses(['#American','#Fiorentina']).
disjointClasses(['#Veneziana','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Veneziana']).
disjointClasses(['#GarlicTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#GarlicTopping']).
disjointClasses(['#LaReine','#Veneziana']).
disjointClasses(['#Veneziana','#LaReine']).
disjointClasses(['#GarlicTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#GarlicTopping']).
disjointClasses(['#LaReine','#Rosa']).
disjointClasses(['#Rosa','#LaReine']).
disjointClasses(['#GarlicTopping','#OnionTopping']).
disjointClasses(['#OnionTopping','#GarlicTopping']).
disjointClasses(['#MozzarellaTopping','#GoatsCheeseTopping']).
disjointClasses(['#GoatsCheeseTopping','#MozzarellaTopping']).
disjointClasses(['#Pizza','#IceCream']).
disjointClasses(['#IceCream','#Pizza']).
disjointClasses(['#QuattroFormaggi','#AmericanHot']).
disjointClasses(['#AmericanHot','#QuattroFormaggi']).
disjointClasses(['#Veneziana','#Soho']).
disjointClasses(['#Soho','#Veneziana']).
disjointClasses(['#GorgonzolaTopping','#GoatsCheeseTopping']).
disjointClasses(['#GoatsCheeseTopping','#GorgonzolaTopping']).
disjointClasses(['#Cajun','#Napoletana']).
disjointClasses(['#Napoletana','#Cajun']).
disjointClasses(['#ArtichokeTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#ArtichokeTopping']).
disjointClasses(['#Caprina','#Veneziana']).
disjointClasses(['#Veneziana','#Caprina']).
disjointClasses(['#Fiorentina','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Fiorentina']).
disjointClasses(['#Cajun','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Cajun']).
disjointClasses(['#ArtichokeTopping','#OnionTopping']).
disjointClasses(['#OnionTopping','#ArtichokeTopping']).
disjointClasses(['#QuattroFormaggi','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#QuattroFormaggi']).
disjointClasses(['#American','#Napoletana']).
disjointClasses(['#Napoletana','#American']).
disjointClasses(['#Giardiniera','#Caprina']).
disjointClasses(['#Caprina','#Giardiniera']).
disjointClasses(['#Fiorentina','#Siciliana']).
disjointClasses(['#Siciliana','#Fiorentina']).
disjointClasses(['#UnclosedPizza','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#UnclosedPizza']).
disjointClasses(['#Caprina','#Rosa']).
disjointClasses(['#Rosa','#Caprina']).
disjointClasses(['#AmericanHot','#Margherita']).
disjointClasses(['#Margherita','#AmericanHot']).
disjointClasses(['#FourSeasons','#Capricciosa']).
disjointClasses(['#Capricciosa','#FourSeasons']).
disjointClasses(['#TomatoTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#TomatoTopping']).
disjointClasses(['#SpinachTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#SpinachTopping']).
disjointClasses(['#IceCream','#PizzaTopping']).
disjointClasses(['#PizzaTopping','#IceCream']).
disjointClasses(['#American','#Margherita']).
disjointClasses(['#Margherita','#American']).
disjointClasses(['#FruttiDiMare','#Fiorentina']).
disjointClasses(['#Fiorentina','#FruttiDiMare']).
disjointClasses(['#PolloAdAstra','#Margherita']).
disjointClasses(['#Margherita','#PolloAdAstra']).
disjointClasses(['#LaReine','#AmericanHot']).
disjointClasses(['#AmericanHot','#LaReine']).
disjointClasses(['#Giardiniera','#AmericanHot']).
disjointClasses(['#AmericanHot','#Giardiniera']).
disjointClasses(['#LeekTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#LeekTopping']).
disjointClasses(['#Veneziana','#AmericanHot']).
disjointClasses(['#AmericanHot','#Veneziana']).
disjointClasses(['#Caprina','#Cajun']).
disjointClasses(['#Cajun','#Caprina']).
disjointClasses(['#Mushroom','#Napoletana']).
disjointClasses(['#Napoletana','#Mushroom']).
disjointClasses(['#QuattroFormaggi','#Margherita']).
disjointClasses(['#Margherita','#QuattroFormaggi']).
disjointClasses(['#American','#Parmense']).
disjointClasses(['#Parmense','#American']).
disjointClasses(['#PizzaBase','#IceCream']).
disjointClasses(['#IceCream','#PizzaBase']).
disjointClasses(['#Cajun','#AmericanHot']).
disjointClasses(['#AmericanHot','#Cajun']).
disjointClasses(['#LaReine','#Siciliana']).
disjointClasses(['#Siciliana','#LaReine']).
disjointClasses(['#PolloAdAstra','#Napoletana']).
disjointClasses(['#Napoletana','#PolloAdAstra']).
disjointClasses(['#FruttiDiMare','#Cajun']).
disjointClasses(['#Cajun','#FruttiDiMare']).
disjointClasses(['#UnclosedPizza','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#UnclosedPizza']).
disjointClasses(['#OnionTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#OnionTopping']).
disjointClasses(['#Giardiniera','#Mushroom']).
disjointClasses(['#Mushroom','#Giardiniera']).
disjointClasses(['#UnclosedPizza','#Fiorentina']).
disjointClasses(['#Fiorentina','#UnclosedPizza']).
disjointClasses(['#Rosa','#Siciliana']).
disjointClasses(['#Siciliana','#Rosa']).
disjointClasses(['#Giardiniera','#Rosa']).
disjointClasses(['#Rosa','#Giardiniera']).
disjointClasses(['#Cajun','#Siciliana']).
disjointClasses(['#Siciliana','#Cajun']).
disjointClasses(['#Veneziana','#Siciliana']).
disjointClasses(['#Siciliana','#Veneziana']).
disjointClasses(['#SauceTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#SauceTopping']).
disjointClasses(['#Giardiniera','#FruttiDiMare']).
disjointClasses(['#FruttiDiMare','#Giardiniera']).
disjointClasses(['#RosemaryTopping','#CajunSpiceTopping']).
disjointClasses(['#CajunSpiceTopping','#RosemaryTopping']).
disjointClasses(['#PrinceCarlo','#Napoletana']).
disjointClasses(['#Napoletana','#PrinceCarlo']).
disjointClasses(['#Soho','#Siciliana']).
disjointClasses(['#Siciliana','#Soho']).
disjointClasses(['#AnchoviesTopping','#MixedSeafoodTopping']).
disjointClasses(['#MixedSeafoodTopping','#AnchoviesTopping']).
disjointClasses(['#FishTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#FishTopping']).
disjointClasses(['#VegetarianPizza','#NonVegetarianPizza']).
disjointClasses(['#NonVegetarianPizza','#VegetarianPizza']).
disjointClasses(['#Siciliana','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Siciliana']).
disjointClasses(['#ThinAndCrispyBase','#DeepPanBase']).
disjointClasses(['#DeepPanBase','#ThinAndCrispyBase']).
disjointClasses(['#SloppyGiuseppe','#Napoletana']).
disjointClasses(['#Napoletana','#SloppyGiuseppe']).
disjointClasses(['#SundriedTomatoTopping','#SlicedTomatoTopping']).
disjointClasses(['#SlicedTomatoTopping','#SundriedTomatoTopping']).
disjointClasses(['#SloppyGiuseppe','#AmericanHot']).
disjointClasses(['#AmericanHot','#SloppyGiuseppe']).
disjointClasses(['#Veneziana','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Veneziana']).
disjointClasses(['#Capricciosa','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Capricciosa']).
disjointClasses(['#MushroomTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#MushroomTopping']).
disjointClasses(['#Veneziana','#Capricciosa']).
disjointClasses(['#Capricciosa','#Veneziana']).
disjointClasses(['#SpinachTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#SpinachTopping']).
disjointClasses(['#Veneziana','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Veneziana']).
disjointClasses(['#Fiorentina','#Veneziana']).
disjointClasses(['#Veneziana','#Fiorentina']).
disjointClasses(['#Capricciosa','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Capricciosa']).
disjointClasses(['#Fiorentina','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Fiorentina']).
disjointClasses(['#Rosa','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Rosa']).
disjointClasses(['#UnclosedPizza','#Parmense']).
disjointClasses(['#Parmense','#UnclosedPizza']).
disjointClasses(['#Giardiniera','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#Giardiniera']).
disjointClasses(['#FourSeasons','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#FourSeasons']).
disjointClasses(['#GarlicTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#GarlicTopping']).
disjointClasses(['#MeatTopping','#FishTopping']).
disjointClasses(['#FishTopping','#MeatTopping']).
disjointClasses(['#Rosa','#Margherita']).
disjointClasses(['#Margherita','#Rosa']).
disjointClasses(['#SloppyGiuseppe','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#SloppyGiuseppe']).
disjointClasses(['#FourSeasons','#Rosa']).
disjointClasses(['#Rosa','#FourSeasons']).
disjointClasses(['#FourSeasons','#AmericanHot']).
disjointClasses(['#AmericanHot','#FourSeasons']).
disjointClasses(['#FruttiDiMare','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#FruttiDiMare']).
disjointClasses(['#Giardiniera','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Giardiniera']).
disjointClasses(['#Caprina','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Caprina']).
disjointClasses(['#AmericanHot','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#AmericanHot']).
disjointClasses(['#MozzarellaTopping','#GorgonzolaTopping']).
disjointClasses(['#GorgonzolaTopping','#MozzarellaTopping']).
disjointClasses(['#Soho','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Soho']).
disjointClasses(['#Mushroom','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#Mushroom']).
disjointClasses(['#Capricciosa','#Soho']).
disjointClasses(['#Soho','#Capricciosa']).
disjointClasses(['#Rosa','#Parmense']).
disjointClasses(['#Parmense','#Rosa']).
disjointClasses(['#TomatoTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#TomatoTopping']).
disjointClasses(['#SpinachTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#SpinachTopping']).
disjointClasses(['#Capricciosa','#Rosa']).
disjointClasses(['#Rosa','#Capricciosa']).
disjointClasses(['#FourCheesesTopping','#ParmesanTopping']).
disjointClasses(['#ParmesanTopping','#FourCheesesTopping']).
disjointClasses(['#Caprina','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Caprina']).
disjointClasses(['#QuattroFormaggi','#American']).
disjointClasses(['#American','#QuattroFormaggi']).
disjointClasses(['#Rosa','#American']).
disjointClasses(['#American','#Rosa']).
disjointClasses(['#Fiorentina','#Parmense']).
disjointClasses(['#Parmense','#Fiorentina']).
disjointClasses(['#FruttiDiMare','#Siciliana']).
disjointClasses(['#Siciliana','#FruttiDiMare']).
disjointClasses(['#Giardiniera','#Fiorentina']).
disjointClasses(['#Fiorentina','#Giardiniera']).
disjointClasses(['#Capricciosa','#Siciliana']).
disjointClasses(['#Siciliana','#Capricciosa']).
disjointClasses(['#Mushroom','#Margherita']).
disjointClasses(['#Margherita','#Mushroom']).
disjointClasses(['#FourSeasons','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#FourSeasons']).
disjointClasses(['#GarlicTopping','#SpinachTopping']).
disjointClasses(['#SpinachTopping','#GarlicTopping']).
disjointClasses(['#AmericanHot','#Parmense']).
disjointClasses(['#Parmense','#AmericanHot']).
disjointClasses(['#PizzaBase','#PizzaTopping']).
disjointClasses(['#PizzaTopping','#PizzaBase']).
disjointClasses(['#Rosa','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Rosa']).
disjointClasses(['#FruitTopping','#NutTopping']).
disjointClasses(['#NutTopping','#FruitTopping']).
disjointClasses(['#GreenPepperTopping','#SweetPepperTopping']).
disjointClasses(['#SweetPepperTopping','#GreenPepperTopping']).
disjointClasses(['#Cajun','#American']).
disjointClasses(['#American','#Cajun']).
disjointClasses(['#FourSeasons','#American']).
disjointClasses(['#American','#FourSeasons']).
disjointClasses(['#CheeseTopping','#FishTopping']).
disjointClasses(['#FishTopping','#CheeseTopping']).
disjointClasses(['#Giardiniera','#Capricciosa']).
disjointClasses(['#Capricciosa','#Giardiniera']).
disjointClasses(['#OnionTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#OnionTopping']).
disjointClasses(['#TomatoTopping','#OnionTopping']).
disjointClasses(['#OnionTopping','#TomatoTopping']).
disjointClasses(['#LaReine','#American']).
disjointClasses(['#American','#LaReine']).
disjointClasses(['#GorgonzolaTopping','#ParmesanTopping']).
disjointClasses(['#ParmesanTopping','#GorgonzolaTopping']).
disjointClasses(['#SpinachTopping','#TomatoTopping']).
disjointClasses(['#TomatoTopping','#SpinachTopping']).
disjointClasses(['#Veneziana','#Rosa']).
disjointClasses(['#Rosa','#Veneziana']).
disjointClasses(['#DomainConcept','#ValuePartition']).
disjointClasses(['#ValuePartition','#DomainConcept']).
disjointClasses(['#Fiorentina','#Capricciosa']).
disjointClasses(['#Capricciosa','#Fiorentina']).
disjointClasses(['#FruttiDiMare','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#FruttiDiMare']).
disjointClasses(['#Soho','#AmericanHot']).
disjointClasses(['#AmericanHot','#Soho']).
disjointClasses(['#ArtichokeTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#ArtichokeTopping']).
disjointClasses(['#JalapenoPepperTopping','#GreenPepperTopping']).
disjointClasses(['#GreenPepperTopping','#JalapenoPepperTopping']).
disjointClasses(['#Capricciosa','#Margherita']).
disjointClasses(['#Margherita','#Capricciosa']).
disjointClasses(['#FruitTopping','#MeatTopping']).
disjointClasses(['#MeatTopping','#FruitTopping']).
disjointClasses(['#ArtichokeTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#ArtichokeTopping']).
disjointClasses(['#LaReine','#FruttiDiMare']).
disjointClasses(['#FruttiDiMare','#LaReine']).
disjointClasses(['#UnclosedPizza','#Veneziana']).
disjointClasses(['#Veneziana','#UnclosedPizza']).
disjointClasses(['#Caprina','#Margherita']).
disjointClasses(['#Margherita','#Caprina']).
disjointClasses(['#Soho','#Margherita']).
disjointClasses(['#Margherita','#Soho']).
disjointClasses(['#FourSeasons','#Parmense']).
disjointClasses(['#Parmense','#FourSeasons']).
disjointClasses(['#LaReine','#Fiorentina']).
disjointClasses(['#Fiorentina','#LaReine']).
disjointClasses(['#AsparagusTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#AsparagusTopping']).
disjointClasses(['#PetitPoisTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#PetitPoisTopping']).
disjointClasses(['#Giardiniera','#Margherita']).
disjointClasses(['#Margherita','#Giardiniera']).
disjointClasses(['#Siciliana','#Parmense']).
disjointClasses(['#Parmense','#Siciliana']).
disjointClasses(['#FruttiDiMare','#American']).
disjointClasses(['#American','#FruttiDiMare']).
disjointClasses(['#OnionTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#OnionTopping']).
disjointClasses(['#LeekTopping','#GarlicTopping']).
disjointClasses(['#GarlicTopping','#LeekTopping']).
disjointClasses(['#Rosa','#Napoletana']).
disjointClasses(['#Napoletana','#Rosa']).
disjointClasses(['#UnclosedPizza','#Rosa']).
disjointClasses(['#Rosa','#UnclosedPizza']).
disjointClasses(['#Caprina','#Parmense']).
disjointClasses(['#Parmense','#Caprina']).
disjointClasses(['#Giardiniera','#Parmense']).
disjointClasses(['#Parmense','#Giardiniera']).
disjointClasses(['#Capricciosa','#AmericanHot']).
disjointClasses(['#AmericanHot','#Capricciosa']).
disjointClasses(['#Giardiniera','#LaReine']).
disjointClasses(['#LaReine','#Giardiniera']).
disjointClasses(['#ArtichokeTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#ArtichokeTopping']).
disjointClasses(['#FruttiDiMare','#Mushroom']).
disjointClasses(['#Mushroom','#FruttiDiMare']).
disjointClasses(['#LeekTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#LeekTopping']).
disjointClasses(['#Soho','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Soho']).
disjointClasses(['#LeekTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#LeekTopping']).
disjointClasses(['#Caprina','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Caprina']).
disjointClasses(['#TomatoTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#TomatoTopping']).
disjointClasses(['#ArtichokeTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#ArtichokeTopping']).
disjointClasses(['#Caprina','#Fiorentina']).
disjointClasses(['#Fiorentina','#Caprina']).
disjointClasses(['#PeperonataTopping','#GreenPepperTopping']).
disjointClasses(['#GreenPepperTopping','#PeperonataTopping']).
disjointClasses(['#JalapenoPepperTopping','#PeperonataTopping']).
disjointClasses(['#PeperonataTopping','#JalapenoPepperTopping']).
disjointClasses(['#UnclosedPizza','#Napoletana']).
disjointClasses(['#Napoletana','#UnclosedPizza']).
disjointClasses(['#AmericanHot','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#AmericanHot']).
disjointClasses(['#LaReine','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#LaReine']).
disjointClasses(['#Mushroom','#American']).
disjointClasses(['#American','#Mushroom']).
disjointClasses(['#PolloAdAstra','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#PolloAdAstra']).
disjointClasses(['#Medium','#Hot']).
disjointClasses(['#Hot','#Medium']).
disjointClasses(['#FourCheesesTopping','#GoatsCheeseTopping']).
disjointClasses(['#GoatsCheeseTopping','#FourCheesesTopping']).
disjointClasses(['#ArtichokeTopping','#SpinachTopping']).
disjointClasses(['#SpinachTopping','#ArtichokeTopping']).
disjointClasses(['#Giardiniera','#Siciliana']).
disjointClasses(['#Siciliana','#Giardiniera']).
disjointClasses(['#FruttiDiMare','#Soho']).
disjointClasses(['#Soho','#FruttiDiMare']).
disjointClasses(['#Mushroom','#Siciliana']).
disjointClasses(['#Siciliana','#Mushroom']).
disjointClasses(['#GarlicTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#GarlicTopping']).
disjointClasses(['#MozzarellaTopping','#ParmesanTopping']).
disjointClasses(['#ParmesanTopping','#MozzarellaTopping']).
disjointClasses(['#RocketTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#RocketTopping']).
disjointClasses(['#UnclosedPizza','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#UnclosedPizza']).
disjointClasses(['#FruitTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#FruitTopping']).
disjointClasses(['#FruttiDiMare','#Caprina']).
disjointClasses(['#Caprina','#FruttiDiMare']).
disjointClasses(['#QuattroFormaggi','#Napoletana']).
disjointClasses(['#Napoletana','#QuattroFormaggi']).
disjointClasses(['#MeatTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#MeatTopping']).
disjointClasses(['#ArtichokeTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#ArtichokeTopping']).
disjointClasses(['#LeekTopping','#ArtichokeTopping']).
disjointClasses(['#ArtichokeTopping','#LeekTopping']).
disjointClasses(['#LeekTopping','#OnionTopping']).
disjointClasses(['#OnionTopping','#LeekTopping']).
disjointClasses(['#FourSeasons','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#FourSeasons']).
disjointClasses(['#Siciliana','#AmericanHot']).
disjointClasses(['#AmericanHot','#Siciliana']).
disjointClasses(['#Caprina','#Mushroom']).
disjointClasses(['#Mushroom','#Caprina']).
disjointClasses(['#LaReine','#Parmense']).
disjointClasses(['#Parmense','#LaReine']).
disjointClasses(['#Soho','#Rosa']).
disjointClasses(['#Rosa','#Soho']).
disjointClasses(['#VegetableTopping','#NutTopping']).
disjointClasses(['#NutTopping','#VegetableTopping']).
disjointClasses(['#Parmense','#Napoletana']).
disjointClasses(['#Napoletana','#Parmense']).
disjointClasses(['#Capricciosa','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Capricciosa']).
disjointClasses(['#LeekTopping','#SpinachTopping']).
disjointClasses(['#SpinachTopping','#LeekTopping']).
disjointClasses(['#PeperonataTopping','#SweetPepperTopping']).
disjointClasses(['#SweetPepperTopping','#PeperonataTopping']).
disjointClasses(['#Caprina','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#Caprina']).
disjointClasses(['#PolloAdAstra','#Parmense']).
disjointClasses(['#Parmense','#PolloAdAstra']).
disjointClasses(['#Capricciosa','#American']).
disjointClasses(['#American','#Capricciosa']).
disjointClasses(['#VegetableTopping','#FruitTopping']).
disjointClasses(['#FruitTopping','#VegetableTopping']).
disjointClasses(['#SloppyGiuseppe','#Parmense']).
disjointClasses(['#Parmense','#SloppyGiuseppe']).
disjointClasses(['#Soho','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Soho']).
disjointClasses(['#FourSeasons','#Cajun']).
disjointClasses(['#Cajun','#FourSeasons']).
disjointClasses(['#Veneziana','#Cajun']).
disjointClasses(['#Cajun','#Veneziana']).
disjointClasses(['#Cajun','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Cajun']).
disjointClasses(['#SpinachTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#SpinachTopping']).
disjointClasses(['#SauceTopping','#FruitTopping']).
disjointClasses(['#FruitTopping','#SauceTopping']).
disjointClasses(['#NutTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#NutTopping']).
disjointClasses(['#Mushroom','#Soho']).
disjointClasses(['#Soho','#Mushroom']).
disjointClasses(['#LaReine','#UnclosedPizza']).
disjointClasses(['#UnclosedPizza','#LaReine']).
disjointClasses(['#Giardiniera','#Napoletana']).
disjointClasses(['#Napoletana','#Giardiniera']).
disjointClasses(['#Medium','#Mild']).
disjointClasses(['#Mild','#Medium']).
disjointClasses(['#CaperTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#CaperTopping']).
disjointClasses(['#Cajun','#Parmense']).
disjointClasses(['#Parmense','#Cajun']).
disjointClasses(['#VegetableTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#VegetableTopping']).
disjointClasses(['#Margherita','#Napoletana']).
disjointClasses(['#Napoletana','#Margherita']).
disjointClasses(['#SpinachTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#SpinachTopping']).
disjointClasses(['#SauceTopping','#VegetableTopping']).
disjointClasses(['#VegetableTopping','#SauceTopping']).
disjointClasses(['#Mushroom','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Mushroom']).
disjointClasses(['#TomatoTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#TomatoTopping']).
disjointClasses(['#GarlicTopping','#TomatoTopping']).
disjointClasses(['#TomatoTopping','#GarlicTopping']).
disjointClasses(['#Fiorentina','#Margherita']).
disjointClasses(['#Margherita','#Fiorentina']).
disjointClasses(['#Cajun','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Cajun']).
disjointClasses(['#Rosa','#AmericanHot']).
disjointClasses(['#AmericanHot','#Rosa']).
disjointClasses(['#Mushroom','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Mushroom']).
disjointClasses(['#UnclosedPizza','#Siciliana']).
disjointClasses(['#Siciliana','#UnclosedPizza']).
disjointClasses(['#PetitPoisTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#PetitPoisTopping']).
disjointClasses(['#Caprina','#LaReine']).
disjointClasses(['#LaReine','#Caprina']).
disjointClasses(['#Mushroom','#Parmense']).
disjointClasses(['#Parmense','#Mushroom']).
disjointClasses(['#VegetableTopping','#MeatTopping']).
disjointClasses(['#MeatTopping','#VegetableTopping']).
disjointClasses(['#Parmense','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Parmense']).
disjointClasses(['#FourSeasons','#Mushroom']).
disjointClasses(['#Mushroom','#FourSeasons']).
disjointClasses(['#Mushroom','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Mushroom']).
disjointClasses(['#PetitPoisTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#PetitPoisTopping']).
disjointClasses(['#FourSeasons','#Giardiniera']).
disjointClasses(['#Giardiniera','#FourSeasons']).
disjointClasses(['#Capricciosa','#Parmense']).
disjointClasses(['#Parmense','#Capricciosa']).
disjointClasses(['#FourSeasons','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#FourSeasons']).
disjointClasses(['#Veneziana','#American']).
disjointClasses(['#American','#Veneziana']).
disjointClasses(['#American','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#American']).
disjointClasses(['#LaReine','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#LaReine']).
disjointClasses(['#Pizza','#PizzaTopping']).
disjointClasses(['#PizzaTopping','#Pizza']).
disjointClasses(['#LeekTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#LeekTopping']).
disjointClasses(['#CaperTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#CaperTopping']).
disjointClasses(['#Giardiniera','#Soho']).
disjointClasses(['#Soho','#Giardiniera']).
disjointClasses(['#FruttiDiMare','#Capricciosa']).
disjointClasses(['#Capricciosa','#FruttiDiMare']).
disjointClasses(['#PrawnsTopping','#MixedSeafoodTopping']).
disjointClasses(['#MixedSeafoodTopping','#PrawnsTopping']).
disjointClasses(['#ArtichokeTopping','#TomatoTopping']).
disjointClasses(['#TomatoTopping','#ArtichokeTopping']).
disjointClasses(['#QuattroFormaggi','#Siciliana']).
disjointClasses(['#Siciliana','#QuattroFormaggi']).
disjointClasses(['#HotSpicedBeefTopping','#HamTopping']).
disjointClasses(['#HamTopping','#HotSpicedBeefTopping']).
disjointClasses(['#OliveTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#OliveTopping']).
disjointClasses(['#Caprina','#Siciliana']).
disjointClasses(['#Siciliana','#Caprina']).
disjointClasses(['#Siciliana','#American']).
disjointClasses(['#American','#Siciliana']).
disjointClasses(['#Fiorentina','#Soho']).
disjointClasses(['#Soho','#Fiorentina']).
disjointClasses(['#Siciliana','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Siciliana']).
disjointClasses(['#Veneziana','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Veneziana']).
disjointClasses(['#SpinachTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#SpinachTopping']).
disjointClasses(['#Mushroom','#Veneziana']).
disjointClasses(['#Veneziana','#Mushroom']).
disjointClasses(['#Giardiniera','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Giardiniera']).
disjointClasses(['#ChickenTopping','#HotSpicedBeefTopping']).
disjointClasses(['#HotSpicedBeefTopping','#ChickenTopping']).
disjointClasses(['#ChickenTopping','#HamTopping']).
disjointClasses(['#HamTopping','#ChickenTopping']).
disjointClasses(['#PrawnsTopping','#AnchoviesTopping']).
disjointClasses(['#AnchoviesTopping','#PrawnsTopping']).
disjointClasses(['#LaReine','#Margherita']).
disjointClasses(['#Margherita','#LaReine']).
disjointClasses(['#FourSeasons','#LaReine']).
disjointClasses(['#LaReine','#FourSeasons']).
disjointClasses(['#GarlicTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#GarlicTopping']).
disjointClasses(['#Giardiniera','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Giardiniera']).
disjointClasses(['#SpinachTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#SpinachTopping']).
disjointClasses(['#ArtichokeTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#ArtichokeTopping']).
disjointClasses(['#Giardiniera','#Veneziana']).
disjointClasses(['#Veneziana','#Giardiniera']).
disjointClasses(['#FourSeasons','#Napoletana']).
disjointClasses(['#Napoletana','#FourSeasons']).
disjointClasses(['#Soho','#Cajun']).
disjointClasses(['#Cajun','#Soho']).
disjointClasses(['#Caprina','#Napoletana']).
disjointClasses(['#Napoletana','#Caprina']).
disjointClasses(['#Fiorentina','#AmericanHot']).
disjointClasses(['#AmericanHot','#Fiorentina']).
disjointClasses(['#Mushroom','#Rosa']).
disjointClasses(['#Rosa','#Mushroom']).
disjointClasses(['#TomatoTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#TomatoTopping']).
disjointClasses(['#PetitPoisTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#PetitPoisTopping']).
disjointClasses(['#UnclosedPizza','#Capricciosa']).
disjointClasses(['#Capricciosa','#UnclosedPizza']).
disjointClasses(['#FruttiDiMare','#Rosa']).
disjointClasses(['#Rosa','#FruttiDiMare']).
disjointClasses(['#OnionTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#OnionTopping']).
disjointClasses(['#MushroomTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#MushroomTopping']).
disjointClasses(['#CheeseTopping','#NutTopping']).
disjointClasses(['#NutTopping','#CheeseTopping']).
disjointClasses(['#SauceTopping','#NutTopping']).
disjointClasses(['#NutTopping','#SauceTopping']).
disjointClasses(['#SloppyGiuseppe','#American']).
disjointClasses(['#American','#SloppyGiuseppe']).
disjointClasses(['#MushroomTopping','#PepperTopping']).
disjointClasses(['#PepperTopping','#MushroomTopping']).
disjointClasses(['#OnionTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#OnionTopping']).
disjointClasses(['#American','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#American']).
disjointClasses(['#Parmense','#Margherita']).
disjointClasses(['#Margherita','#Parmense']).
disjointClasses(['#FourSeasons','#Soho']).
disjointClasses(['#Soho','#FourSeasons']).
disjointClasses(['#FruttiDiMare','#Margherita']).
disjointClasses(['#Margherita','#FruttiDiMare']).
disjointClasses(['#LeekTopping','#PetitPoisTopping']).
disjointClasses(['#PetitPoisTopping','#LeekTopping']).
disjointClasses(['#Giardiniera','#American']).
disjointClasses(['#American','#Giardiniera']).
disjointClasses(['#RocketTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#RocketTopping']).
disjointClasses(['#FourSeasons','#FruttiDiMare']).
disjointClasses(['#FruttiDiMare','#FourSeasons']).
disjointClasses(['#UnclosedPizza','#Cajun']).
disjointClasses(['#Cajun','#UnclosedPizza']).
disjointClasses(['#FourCheesesTopping','#MozzarellaTopping']).
disjointClasses(['#MozzarellaTopping','#FourCheesesTopping']).
disjointClasses(['#Giardiniera','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Giardiniera']).
disjointClasses(['#Giardiniera','#Cajun']).
disjointClasses(['#Cajun','#Giardiniera']).
disjointClasses(['#FruttiDiMare','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#FruttiDiMare']).
disjointClasses(['#QuattroFormaggi','#Parmense']).
disjointClasses(['#Parmense','#QuattroFormaggi']).
disjointClasses(['#FourSeasons','#Veneziana']).
disjointClasses(['#Veneziana','#FourSeasons']).
disjointClasses(['#ChickenTopping','#PeperoniSausageTopping']).
disjointClasses(['#PeperoniSausageTopping','#ChickenTopping']).
disjointClasses(['#SloppyGiuseppe','#Margherita']).
disjointClasses(['#Margherita','#SloppyGiuseppe']).
disjointClasses(['#SauceTopping','#CheeseTopping']).
disjointClasses(['#CheeseTopping','#SauceTopping']).
disjointClasses(['#OnionTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#OnionTopping']).
disjointClasses(['#Capricciosa','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Capricciosa']).
disjointClasses(['#LaReine','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#LaReine']).
disjointClasses(['#LaReine','#Soho']).
disjointClasses(['#Soho','#LaReine']).
disjointClasses(['#PeperoniSausageTopping','#HamTopping']).
disjointClasses(['#HamTopping','#PeperoniSausageTopping']).
disjointClasses(['#Veneziana','#Margherita']).
disjointClasses(['#Margherita','#Veneziana']).
disjointClasses(['#Fiorentina','#Rosa']).
disjointClasses(['#Rosa','#Fiorentina']).
disjointClasses(['#UnclosedPizza','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#UnclosedPizza']).
disjointClasses(['#AmericanHot','#Napoletana']).
disjointClasses(['#Napoletana','#AmericanHot']).
disjointClasses(['#TomatoTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#TomatoTopping']).
disjointClasses(['#PizzaBase','#Pizza']).
disjointClasses(['#Pizza','#PizzaBase']).
disjointClasses(['#Soho','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Soho']).
disjointClasses(['#VegetableTopping','#FishTopping']).
disjointClasses(['#FishTopping','#VegetableTopping']).
disjointClasses(['#RocketTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#RocketTopping']).
disjointClasses(['#Capricciosa','#Napoletana']).
disjointClasses(['#Napoletana','#Capricciosa']).
disjointClasses(['#American','#AmericanHot']).
disjointClasses(['#AmericanHot','#American']).
disjointClasses(['#JalapenoPepperTopping','#SweetPepperTopping']).
disjointClasses(['#SweetPepperTopping','#JalapenoPepperTopping']).
disjointClasses(['#FourSeasons','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#FourSeasons']).
disjointClasses(['#Margherita','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Margherita']).
disjointClasses(['#FourSeasons','#Caprina']).
disjointClasses(['#Caprina','#FourSeasons']).
disjointClasses(['#GoatsCheeseTopping','#ParmesanTopping']).
disjointClasses(['#ParmesanTopping','#GoatsCheeseTopping']).
disjointClasses(['#FruitTopping','#FishTopping']).
disjointClasses(['#FishTopping','#FruitTopping']).
disjointClasses(['#TomatoTopping','#AsparagusTopping']).
disjointClasses(['#AsparagusTopping','#TomatoTopping']).
disjointClasses(['#Rosa','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Rosa']).
disjointClasses(['#Soho','#Napoletana']).
disjointClasses(['#Napoletana','#Soho']).
disjointClasses(['#Capricciosa','#Cajun']).
disjointClasses(['#Cajun','#Capricciosa']).
disjointClasses(['#Cajun','#Rosa']).
disjointClasses(['#Rosa','#Cajun']).
disjointClasses(['#CheeseTopping','#FruitTopping']).
disjointClasses(['#FruitTopping','#CheeseTopping']).
disjointClasses(['#QuattroFormaggi','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#QuattroFormaggi']).
disjointClasses(['#Caprina','#AmericanHot']).
disjointClasses(['#AmericanHot','#Caprina']).
disjointClasses(['#RocketTopping','#OliveTopping']).
disjointClasses(['#OliveTopping','#RocketTopping']).
disjointClasses(['#LaReine','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#LaReine']).
disjointClasses(['#MeatTopping','#NutTopping']).
disjointClasses(['#NutTopping','#MeatTopping']).
disjointClasses(['#RocketTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#RocketTopping']).
disjointClasses(['#LaReine','#Napoletana']).
disjointClasses(['#Napoletana','#LaReine']).
disjointClasses(['#FourSeasons','#Fiorentina']).
disjointClasses(['#Fiorentina','#FourSeasons']).
disjointClasses(['#Mushroom','#AmericanHot']).
disjointClasses(['#AmericanHot','#Mushroom']).
disjointClasses(['#Fiorentina','#Napoletana']).
disjointClasses(['#Napoletana','#Fiorentina']).
disjointClasses(['#GarlicTopping','#RocketTopping']).
disjointClasses(['#RocketTopping','#GarlicTopping']).
disjointClasses(['#FourSeasons','#Margherita']).
disjointClasses(['#Margherita','#FourSeasons']).
disjointClasses(['#Cajun','#Margherita']).
disjointClasses(['#Margherita','#Cajun']).
disjointClasses(['#QuattroFormaggi','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#QuattroFormaggi']).
disjointClasses(['#Caprina','#SloppyGiuseppe']).
disjointClasses(['#SloppyGiuseppe','#Caprina']).
disjointClasses(['#Rosa','#QuattroFormaggi']).
disjointClasses(['#QuattroFormaggi','#Rosa']).
disjointClasses(['#NutTopping','#FishTopping']).
disjointClasses(['#FishTopping','#NutTopping']).
disjointClasses(['#CheeseTopping','#MeatTopping']).
disjointClasses(['#MeatTopping','#CheeseTopping']).
disjointClasses(['#CheeseTopping','#HerbSpiceTopping']).
disjointClasses(['#HerbSpiceTopping','#CheeseTopping']).
disjointClasses(['#PetitPoisTopping','#CaperTopping']).
disjointClasses(['#CaperTopping','#PetitPoisTopping']).
disjointClasses(['#FourCheesesTopping','#GorgonzolaTopping']).
disjointClasses(['#GorgonzolaTopping','#FourCheesesTopping']).
disjointClasses(['#Fiorentina','#PrinceCarlo']).
disjointClasses(['#PrinceCarlo','#Fiorentina']).
disjointClasses(['#Cajun','#PolloAdAstra']).
disjointClasses(['#PolloAdAstra','#Cajun']).
disjointClasses(['#LeekTopping','#TomatoTopping']).
disjointClasses(['#TomatoTopping','#LeekTopping']).
disjointClasses(['#FruttiDiMare','#Napoletana']).
disjointClasses(['#Napoletana','#FruttiDiMare']).
disjointClasses(['#Veneziana','#Parmense']).
disjointClasses(['#Parmense','#Veneziana']).
disjointClasses(['#FourSeasons','#Siciliana']).
disjointClasses(['#Siciliana','#FourSeasons']).
disjointClasses(['#CaperTopping','#MushroomTopping']).
disjointClasses(['#MushroomTopping','#CaperTopping']).
subPropertyOf('#hasTopping','#hasIngredient').
subPropertyOf('#isToppingOf','#isIngredientOf').
subPropertyOf('#isBaseOf','#isIngredientOf').
subPropertyOf('#hasBase','#hasIngredient').
inverseProperties('#hasBase','#isBaseOf').
inverseProperties('#hasIngredient','#isIngredientOf').
inverseProperties('#hasTopping','#isToppingOf').
inverseProperties('#isBaseOf','#hasBase').
inverseProperties('#isIngredientOf','#hasIngredient').
inverseProperties('#isToppingOf','#hasTopping').
propertyDomain('#hasBase','#Pizza').
propertyDomain('#hasIngredient','#Food').
propertyDomain('#hasTopping','#Pizza').
propertyDomain('#isBaseOf','#PizzaBase').
propertyDomain('#isIngredientOf','#Food').
propertyDomain('#isToppingOf','#PizzaTopping').
propertyRange('#hasBase','#PizzaBase').
propertyRange('#hasIngredient','#Food').
propertyRange('#hasSpiciness','#Spiciness').
propertyRange('#hasTopping','#PizzaTopping').
propertyRange('#isBaseOf','#Pizza').
propertyRange('#isIngredientOf','#Food').
propertyRange('#isToppingOf','#Pizza').
functionalProperty('#hasBase').
functionalProperty('#hasSpiciness').
functionalProperty('#isBaseOf').
functionalProperty('#isToppingOf').
inverseFunctionalProperty('#hasBase').
inverseFunctionalProperty('#hasTopping').
inverseFunctionalProperty('#isBaseOf').
transitiveProperty('#hasIngredient').
transitiveProperty('#isIngredientOf').
differentIndividuals(['#America','#Italy','#Germany','#France','#England']).
classAssertion('http://www.w3.org/2002/07/owl#Thing','#America').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#America').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#America').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Italy').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Italy').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Italy').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Germany').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Germany').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#Germany').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#France').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#France').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#France').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#England').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#England').
classAssertion('http://www.w3.org/2002/07/owl#Thing','#England').
classAssertion('#Country','#America').
classAssertion('#Country','#England').
classAssertion('#Country','#France').
classAssertion('#Country','#Germany').
classAssertion('#Country','#Italy').
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#American',literal(lang(pt,'Americana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#AmericanHot',literal(lang(pt,'AmericanaPicante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#AnchoviesTopping',literal(lang(pt,'CoberturaDeAnchovies'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ArtichokeTopping',literal(lang(pt,'CoberturaDeArtichoke'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#AsparagusTopping',literal(lang(pt,'CoberturaDeAspargos'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Cajun',literal(lang(pt,'Cajun'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#CajunSpiceTopping',literal(lang(pt,'CoberturaDeCajun'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#CaperTopping',literal(lang(pt,'CoberturaDeCaper'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Capricciosa',literal(lang(pt,'Capricciosa'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Caprina',literal(lang(pt,'Caprina'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#CheeseTopping',literal(lang(pt,'CoberturaDeQueijo'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#CheeseyPizza',literal(lang(pt,'PizzaComQueijo'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#CheeseyVegetableTopping',literal(lang(pt,'CoberturaDeQueijoComVegetais'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ChickenTopping',literal(lang(pt,'CoberturaDeFrango'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Country',literal(lang(pt,'Pais'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#DeepPanBase',literal(lang(pt,'BaseEspessa'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Fiorentina',literal(lang(pt,'Fiorentina'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#FishTopping',literal(lang(pt,'CoberturaDePeixe'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#FourCheesesTopping',literal(lang(pt,'CoberturaQuatroQueijos'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#FourSeasons',literal(lang(pt,'QuatroQueijos'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#FruitTopping',literal(lang(pt,'CoberturaDeFrutas'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#FruttiDiMare',literal(lang(pt,'FrutosDoMar'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#GarlicTopping',literal(lang(pt,'CoberturaDeAlho'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Giardiniera',literal(lang(pt,'Giardiniera'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#GoatsCheeseTopping',literal(lang(pt,'CoberturaDeQueijoDeCabra'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#GorgonzolaTopping',literal(lang(pt,'CoberturaDeGorgonzola'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#GreenPepperTopping',literal(lang(pt,'CoberturaDePimentaoVerde'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#HamTopping',literal(lang(pt,'CoberturaDePresunto'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#HerbSpiceTopping',literal(lang(pt,'CoberturaDeErvas'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Hot',literal(lang(pt,'Picante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#HotGreenPepperTopping',literal(lang(pt,'CoberturaDePimentaoVerdePicante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#HotSpicedBeefTopping',literal(lang(pt,'CoberturaDeBifePicante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#IceCream',literal(lang(pt,'Sorvete'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#InterestingPizza',literal(lang(pt,'PizzaInteressante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#JalapenoPepperTopping',literal(lang(pt,'CoberturaDeJalapeno'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#LaReine',literal(lang(pt,'LaReine'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#LeekTopping',literal(lang(pt,'CoberturaDeLeek'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Margherita',literal(lang(pt,'Margherita'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#MeatTopping',literal(lang(pt,'CoberturaDeCarne'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#MeatyPizza',literal(lang(pt,'PizzaDeCarne'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Medium',literal(lang(pt,'Media'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Mild',literal(lang(pt,'NaoPicante'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#MixedSeafoodTopping',literal(lang(pt,'CoberturaDeFrutosDoMarMistos'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#MozzarellaTopping',literal(lang(pt,'CoberturaDeMozzarella'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Mushroom',literal(lang(pt,'Cogumelo'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#MushroomTopping',literal(lang(pt,'CoberturaDeCogumelo'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#NamedPizza',literal(lang(pt,'PizzaComUmNome'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Napoletana',literal(lang(pt,'Napoletana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#NonVegetarianPizza',literal(lang(pt,'PizzaNaoVegetariana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#NutTopping',literal(lang(pt,'CoberturaDeCastanha'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#OliveTopping',literal(lang(pt,'CoberturaDeAzeitona'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#OnionTopping',literal(lang(pt,'CoberturaDeCebola'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ParmaHamTopping',literal(lang(pt,'CoberturaDePrezuntoParma'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Parmense',literal(lang(pt,'Parmense'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ParmesanTopping',literal(lang(pt,'CoberturaDeParmesao'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PeperonataTopping',literal(lang(pt,'CoberturaPeperonata'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PeperoniSausageTopping',literal(lang(pt,'CoberturaDeCalabreza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PepperTopping',literal(lang(pt,'CoberturaDePimentao'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PetitPoisTopping',literal(lang(pt,'CoberturaPetitPois'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PineKernels',literal(lang(pt,'CoberturaPineKernels'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Pizza',literal(lang(en,'Pizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PizzaBase',literal(lang(pt,'BaseDaPizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PizzaTopping',literal(lang(pt,'CoberturaDaPizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PolloAdAstra',literal(lang(pt,'PolloAdAstra'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PrawnsTopping',literal(lang(pt,'CoberturaDeCamarao'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#PrinceCarlo',literal(lang(pt,'CoberturaPrinceCarlo'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#QuattroFormaggi',literal(lang(pt,'QuatroQueijos'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#RealItalianPizza',literal(lang(pt,'PizzaItalianaReal'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#RedOnionTopping',literal(lang(pt,'CoberturaDeCebolaVermelha'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#RocketTopping',literal(lang(pt,'CoberturaRocket'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Rosa',literal(lang(pt,'Rosa'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#RosemaryTopping',literal(lang(pt,'CoberturaRosemary'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SauceTopping',literal(lang(pt,'CoberturaEmMolho'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Siciliana',literal(lang(pt,'Siciliana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SlicedTomatoTopping',literal(lang(pt,'CoberturaDeTomateFatiado'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SloppyGiuseppe',literal(lang(pt,'SloppyGiuseppe'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Soho',literal(lang(pt,'Soho'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Spiciness',literal(lang(pt,'Tempero'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SpicyPizza',literal(lang(pt,'PizzaTemperada'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SpicyPizzaEquivalent',literal(lang(pt,'PizzaTemperadaEquivalente'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SpicyTopping',literal(lang(pt,'CoberturaTemperada'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SpinachTopping',literal(lang(pt,'CoberturaDeEspinafre'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SultanaTopping',literal(lang(pt,'CoberturaSultana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SundriedTomatoTopping',literal(lang(pt,'CoberturaDeTomateRessecadoAoSol'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#SweetPepperTopping',literal(lang(pt,'CoberturaDePimentaoDoce'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ThinAndCrispyBase',literal(lang(pt,'BaseFinaEQuebradica'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#TobascoPepperSauce',literal(lang(pt,'MolhoTobascoPepper'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#TomatoTopping',literal(lang(pt,'CoberturaDeTomate'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#UnclosedPizza',literal(lang(pt,'PizzaAberta'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#ValuePartition',literal(lang(pt,'ValorDaParticao'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#VegetableTopping',literal(lang(pt,'CoberturaDeVegetais'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#VegetarianPizza',literal(lang(pt,'PizzaVegetariana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#VegetarianPizzaEquivalent1',literal(lang(pt,'PizzaVegetarianaEquivalente1'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#VegetarianPizzaEquivalent2',literal(lang(pt,'PizzaVegetarianaEquivalente2'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#VegetarianTopping',literal(lang(pt,'CoberturaVegetariana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#label','#Veneziana',literal(lang(pt,'Veneziana'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','',literal(lang(en,'An example ontology that contains all constructs required for the various versions of the Pizza Tutorial run by Manchester University (see http://www.co-ode.org/resources/tutorials/)'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#CheeseyPizza',literal(lang(en,'Any pizza that has at least 1 cheese topping.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#CheeseyVegetableTopping',literal(lang(en,'This class will be inconsistent. This is because we have given it 2 disjoint parents, which means it could never have any members (as nothing can simultaneously be a CheeseTopping and a VegetableTopping). NB Called ProbeInconsistentTopping in the ProtegeOWL Tutorial.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#Country',literal(lang(en,'A class that is equivalent to the set of individuals that are described in the enumeration - ie Countries can only be either America, England, France, Germany or Italy and nothing else. Note that these individuals have been asserted to be allDifferent from each other.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#IceCream',literal(lang(en,'A class to demonstrate mistakes made with setting a property domain. The property hasTopping has a domain of Pizza. This means that the reasoner can infer that all individuals using the hasTopping property must be of type Pizza. Because of the restriction on this class, all members of IceCream must use the hasTopping property, and therefore must also be members of Pizza. However, Pizza and IceCream are disjoint, so this causes an inconsistency. If they were not disjoint, IceCream would be inferred to be a subclass of Pizza.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#InterestingPizza',literal(lang(en,'Any pizza that has at least 3 toppings. Note that this is a cardinality constraint on the hasTopping property and NOT a qualified cardinality constraint (QCR). A QCR would specify from which class the members in this relationship must be. eg has at least 3 toppings from PizzaTopping. This is currently not supported in OWL.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#MeatyPizza',literal(lang(en,'Any pizza that has at least one meat topping'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#NamedPizza',literal(lang(en,'A pizza that can be found on a pizza menu'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#NonVegetarianPizza',literal(lang(en,'Any Pizza that is not a VegetarianPizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#RealItalianPizza',literal(lang(en,'This defined class has conditions that are part of the definition: ie any Pizza that has the country of origin, Italy is a RealItalianPizza. It also has conditions that merely describe the members - that all RealItalianPizzas must only have ThinAndCrispy bases. In essence, all pizzas from Italy must have ThinAndCrispy bases.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#Spiciness',literal(lang(en,'A ValuePartition that describes only values from Hot, Medium or Mild. NB Subclasses can themselves be divided up into further partitions.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#SpicyPizza',literal(lang(en,'Any pizza that has a spicy topping is a SpicyPizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#SpicyPizzaEquivalent',literal(lang(en,'An alternative definition for the SpicyPizza which does away with needing a definition of SpicyTopping and uses a slightly more complicated restriction: Pizzas that have at least one topping that is both a PizzaTopping and has spiciness hot are members of this class.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#SpicyTopping',literal(lang(en,'Any pizza topping that has spiciness Hot'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#UnclosedPizza',literal(type('http://www.w3.org/2001/XMLSchema#string','An unclosed Pizza cannot be inferred to be either a VegetarianPizza or a NonVegetarianPizza, because it might have other toppings.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#ValuePartition',literal(type('http://www.w3.org/2001/XMLSchema#string','A ValuePartition is a pattern that describes a restricted set of classes from which a property can be associated. The parent class is used in restrictions, and the covering axiom means that only members of the subclasses may be used as values. The possible subclasses cannot be extended without updating the ValuePartition class.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#VegetarianPizza',literal(lang(en,'Any pizza that does not have fish topping and does not have meat topping is a VegetarianPizza. Members of this class do not need to have any toppings at all.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#VegetarianPizzaEquivalent1',literal(lang(en,'Any pizza that only has vegetarian toppings or no toppings is a VegetarianPizzaEquiv1. Should be inferred to be equivalent to VegetarianPizzaEquiv2.  Not equivalent to VegetarianPizza because PizzaTopping is not covering'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#VegetarianPizzaEquivalent2',literal(lang(en,'An alternative to VegetarianPizzaEquiv1 that does not require a definition of VegetarianTopping. Perhaps more difficult to maintain. Not equivalent to VegetarianPizza'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#VegetarianTopping',literal(lang(en,'An example of a covering axiom. VegetarianTopping is equivalent to the union of all toppings in the given axiom. VegetarianToppings can only be Cheese or Vegetable or....etc.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#hasIngredient',literal(lang(en,'NB Transitive - the ingredients of ingredients are ingredients of the whole'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#hasSpiciness',literal(lang(en,'A property created to be used with the ValuePartition - Spiciness.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#hasTopping',literal(lang(en,'Note that hasTopping is inverse functional because isToppingOf is functional'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#isIngredientOf',literal(lang(en,'The inverse property tree to hasIngredient - all subproperties and attributes of the properties should reflect those under hasIngredient.'))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','#isToppingOf',literal(lang(en,'Any given instance of topping should only be added to a single pizza (no cheap half-measures on our pizzas)'))).
