/* 1 */  subClassOf(intersectionOf($complementOf(RieslingSugar)$,$RieslingSugar$),owl:Nothing).
/* 2 */  subClassOf($allValuesFrom(hasSugar,RieslingSugar)$,allValuesFrom(hasSugar,$RieslingSugar$)).
/* 3 */  subClassOf(someValuesFrom(hasColor,$White$),$someValuesFrom(hasColor,White)$).
/* 4 */  subClassOf($someValuesFrom(hasColor,White)$,someValuesFrom(hasColor,$White$)).
/* 5 */  subClassOf(someValuesFrom(hasSugar,$DrySugar$),$someValuesFrom(hasSugar,DrySugar)$).
/* 6 */  subClassOf($someValuesFrom(hasSugar,DrySugar)$,someValuesFrom(hasSugar,$DrySugar$)).
/* 7 */  subClassOf(someValuesFrom(hasSugar,$Sugar$),$someValuesFrom(hasSugar,Sugar)$).
/* 8 */  subClassOf($someValuesFrom(hasSugar,Sugar)$,someValuesFrom(hasSugar,$Sugar$)).
/* 9 */  subClassOf($someValuesFrom(hasSugar,complementOf(RieslingSugar))$,someValuesFrom(hasSugar,$complementOf(RieslingSugar)$)).
/* 10 */ subClassOf($DrySugar$,$Sugar$).
/* 11 */ subClassOf($DryWine$,$Wine$).
/* 12 */ subClassOf($Riesling$,$Wine$).
/* 13 */ subClassOf($RieslingGrape$,$Grape$).
/* 14 */ subClassOf($RieslingSugar$,$DrySugar$).
/* 15 */ subClassOf($White$,$Color$).
/* 16 */ subClassOf($WhiteWine$,$Wine$).
/* 17 */ subClassOf($DryWine$,$someValuesFrom(hasSugar,DrySugar)$).
/* 18 */ subClassOf($someValuesFrom(hasSugar,DrySugar)$,$DryWine$).
/* 19 */ subClassOf($Riesling$,$someValuesFrom(hasColor,White)$).
/* 10 */ subClassOf($someValuesFrom(hasColor,White)$,$Riesling$).
/* 21 */ subClassOf($Riesling$,$allValuesFrom(hasSugar,RieslingSugar)$).
/* 22 */ subClassOf($complementOf(someValuesFrom(hasSugar,complementOf(RieslingSugar)))$,$Riesling$).
/* 23 */ subClassOf($WhiteWine$,$someValuesFrom(hasColor,White)$).
/* 24 */ subClassOf($someValuesFrom(hasColor,White)$,$WhiteWine$).
/* 25 */ subClassOf($Wine$,$someValuesFrom(hasSugar,Sugar)$).
/* 26 */ subClassOf($someValuesFrom(hasSugar,Sugar)$,$Wine$).